// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for Salipur Autonomous College - BCA Dept.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgipPKP7c5OGfMEgBLbW_tlZND76eon-g',
    appId: '1:447716952637:web:d9b1b18c24151c5a01b854',
    messagingSenderId: '447716952637',
    projectId: 'bca-department-management-app',
    authDomain: 'bca-department-management-app.firebaseapp.com',
    storageBucket: 'bca-department-management-app.firebasestorage.app',
    measurementId: 'G-JFK9GDFWK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANryWJkbsSdsbLyQShg5itgq91DwCwFPM',
    appId: '1:447716952637:android:798d0d2e6f0cd83301b854',
    messagingSenderId: '447716952637',
    projectId: 'bca-department-management-app',
    storageBucket: 'bca-department-management-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA71fOdMj8xaoNAWtci-nAHURa3EEbfbrQ',
    appId: '1:447716952637:ios:fd2f13f420c8a0f701b854',
    messagingSenderId: '447716952637',
    projectId: 'bca-department-management-app',
    storageBucket: 'bca-department-management-app.firebasestorage.app',
    iosBundleId: 'com.example.bcaDepartmentManagement',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA71fOdMj8xaoNAWtci-nAHURa3EEbfbrQ',
    appId: '1:447716952637:ios:fd2f13f420c8a0f701b854',
    messagingSenderId: '447716952637',
    projectId: 'bca-department-management-app',
    storageBucket: 'bca-department-management-app.firebasestorage.app',
    iosBundleId: 'com.example.bcaDepartmentManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgipPKP7c5OGfMEgBLbW_tlZND76eon-g',
    appId: '1:447716952637:web:2c0139abb19da13f01b854',
    messagingSenderId: '447716952637',
    projectId: 'bca-department-management-app',
    authDomain: 'bca-department-management-app.firebaseapp.com',
    storageBucket: 'bca-department-management-app.firebasestorage.app',
    measurementId: 'G-FM5E160ZNP',
  );
}
