// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for Salipur Autonomous College - BCA Dept.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd1F7ALKfsOORhtloAn9HdlmdSRWie8mA',
    appId: '1:86837758129:web:84c21c18159dbdd2a0ba90',
    messagingSenderId: '86837758129',
    projectId: 'bca-department-management',
    authDomain: 'bca-department-management.firebaseapp.com',
    storageBucket: 'bca-department-management.firebasestorage.app',
    measurementId: 'G-5SHQE82TEJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYXoVBIXQoHM73fI8k_MjQ4bb759S6or4',
    appId: '1:86837758129:android:036ef8cfa24ecc7ba0ba90',
    messagingSenderId: '86837758129',
    projectId: 'bca-department-management',
    storageBucket: 'bca-department-management.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAlo_mR3zEzzmNTXlsjvaQGhYCBvXsfSI',
    appId: '1:86837758129:ios:0eeb6734bcf9be36a0ba90',
    messagingSenderId: '86837758129',
    projectId: 'bca-department-management',
    storageBucket: 'bca-department-management.firebasestorage.app',
    iosBundleId: 'com.example.bcaDepartmentManagement',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAlo_mR3zEzzmNTXlsjvaQGhYCBvXsfSI',
    appId: '1:86837758129:ios:0eeb6734bcf9be36a0ba90',
    messagingSenderId: '86837758129',
    projectId: 'bca-department-management',
    storageBucket: 'bca-department-management.firebasestorage.app',
    iosBundleId: 'com.example.bcaDepartmentManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBd1F7ALKfsOORhtloAn9HdlmdSRWie8mA',
    appId: '1:86837758129:web:b7415757024aabaca0ba90',
    messagingSenderId: '86837758129',
    projectId: 'bca-department-management',
    authDomain: 'bca-department-management.firebaseapp.com',
    storageBucket: 'bca-department-management.firebasestorage.app',
    measurementId: 'G-LTMN6EMJ5G',
  );
}
